version: '3.9'

services:
  db:
      restart: always
      image: postgres:latest
      volumes:
        - db:/var/lib/postgresql/data
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
      ports:
          - '5432:5432'
      env_file:
        - .env
volumes:
  db:
    driver: local